version: "3.8"
services:
  walletapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mydb;Username=myuser;Password=mypassword
    depends_on:
      - postgres  
    container_name: walletapp-api
    restart: unless-stopped  

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    restart: unless-stopped 

volumes:
  postgres-data: 
