name: .NET CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install Dependencies
      run: dotnet restore

    - name: Build and Test
      run: |
        dotnet build --no-restore --configuration Release
        dotnet test --no-build --verbosity normal

    # - name: Publish Docker Image
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     docker build -t walletapp-api .
    #     docker tag walletapp-api ghcr.io/<your-username>/walletapp-api:latest
    #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u <your-username> --password-stdin
    #     docker push ghcr.io/<your-username>/walletapp-api:latest
